export default function handler(req, res) {
  res.status(200).json({
    total: 12,
    results: [
      {
        id: 2912630,
        shortcode: "BE9497F326",
        title: "Freelance reports subeditor",
        remote: false,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "London",
          region: "England",
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2023-01-11T00:00:00.000Z",
        type: "contract",
        language: "en",
        department: ["Editorial"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
      {
        id: 2912654,
        shortcode: "72F6C13AF0",
        title: "Freelance subeditor",
        remote: false,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "London",
          region: "England",
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2023-01-11T00:00:00.000Z",
        type: "full",
        language: "en",
        department: ["Editorial"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
      {
        id: 2901486,
        shortcode: "DD86694F62",
        title: "Event marketing executive",
        remote: false,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "London",
          region: "England",
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2023-01-05T00:00:00.000Z",
        type: "full",
        language: "en",
        department: ["Commercial"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
      {
        id: 2397537,
        shortcode: "B5FE03B774",
        title: "Startup Analyst",
        remote: false,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "London",
          region: "England",
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2022-12-23T00:00:00.000Z",
        type: "full",
        language: "en",
        department: ["Intelligence"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
      {
        id: 2851491,
        shortcode: "BBEDEF1DE0",
        title: "Membership manager",
        remote: false,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "London",
          region: "England",
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2022-12-02T00:00:00.000Z",
        type: "full",
        language: "en",
        department: ["Intelligence"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
      {
        id: 2842194,
        shortcode: "C5F5B41819",
        title: "Events content producer & Digital project manager",
        remote: false,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "London",
          region: "England",
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2022-11-28T00:00:00.000Z",
        type: "full",
        language: "en",
        department: ["Commercial"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
      {
        id: 2794122,
        shortcode: "541FC0EAAA",
        title: "Business development executive",
        remote: false,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "London",
          region: "England",
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2022-11-01T00:00:00.000Z",
        type: "full",
        language: "en",
        department: ["Commercial"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
      {
        id: 2794221,
        shortcode: "55E425FF1E",
        title: "Business development manager",
        remote: false,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "London",
          region: "England",
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2022-11-01T00:00:00.000Z",
        type: "full",
        language: "en",
        department: ["Commercial"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
      {
        id: 2794277,
        shortcode: "5E7BC67F98",
        title: "Senior front-end engineer",
        remote: true,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "",
          region: null,
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2022-11-01T00:00:00.000Z",
        type: "full",
        language: "en",
        department: ["Product"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
      {
        id: 2779450,
        shortcode: "285A38DDE9",
        title: "Senior finance reporter",
        remote: true,
        location: {
          country: "United Kingdom",
          countryCode: "GB",
          city: "",
          region: null,
        },
        state: "published",
        isInternal: false,
        code: "",
        published: "2022-10-24T00:00:00.000Z",
        type: "full",
        language: "en",
        department: ["Editorial"],
        accountUid: "95396c48-357a-49b4-8c6e-6582587d4bbf",
        approvalStatus: "approved",
      },
    ],
    nextPage: "WzE2NjY1Njk2MDAwMDAsMjc3OTQ1MF0=",
  });
}
